---
pg_version: &pg_version '9.5'

versions:
  dumb-init: &dumbinit_version '1.2.1-1'
  geos: &geos_version '3.6.2-1'
  hoot-gdal: &gdal_version '2.1.4-1'
  hoot-words: &words_version '1.0.1-1'
  FileGDBAPI: &filegdbapi_version '1.5.1-1'
  libgeotiff: &libgeotiff_version '1.4.2-1'
  libkml: &libkml_version '1.3.0-1'
  mocha: &mocha_version '3.5.3'
  nodejs: &node_version '8.9.3-1'
  osmosis: &osmosis_version '0.46-1'
  postgis: &postgis_version '2.3.5-1'
  stxxl: &stxxl_version '1.3.1-1'
  su-exec: &suexec_version '0.2-1'
  tomcat8: &tomcat8_version '8.5.24-1'
  wamerican-insane: &wamerican_version '7.1-1'


base_images: !!omap
  - rpmbuild:
      args:
        rpmbuild_dist: .el7
        rpmbuild_uid: 1000
  - rpmbuild-base: {}
  - rpmbuild-generic: {}
  - rpmbuild-pgdg:
      args:
        pg_version: *pg_version
      tags: [*pg_version]
  - rpmbuild-repo: {}
  - rpmbuild-geos:
      buildrequires: true
      dockerfile: 'docker/Dockerfile.rpmbuild-generic'
  - rpmbuild-libgeotiff:
      buildrequires: true
      dockerfile: 'docker/Dockerfile.rpmbuild-generic'
  - rpmbuild-libkml:
      buildrequires: true
      dockerfile: 'docker/Dockerfile.rpmbuild-generic'
  - rpmbuild-nodejs:
      buildrequires: true
      dockerfile: 'docker/Dockerfile.rpmbuild-generic'

# - rpmbuild-gdal:
#     args:
#       filegdbapi_version: *filegdbapi_version
#       geos_version: *geos_version
#       libgeotiff_version: *libgeotiff_version
#       libkml_version: *libkml_version
#       pg_version: *pg_version
#     buildrequires: true
#     spec_file: 'SPECS/hoot-gdal.spec'
# - rpmbuild-postgis:
#     args:
#       gdal_version: *gdal_version
#     buildrequires: true
#     spec_file: 'SPECS/hoot-postgis23.spec'


rpms:
  dumb-init:
    image: rpmbuild-generic
    version: *dumbinit_version
  FileGDBAPI:
    image: rpmbuild-generic
    version: *filegdbapi_version
  osmosis:
    image: rpmbuild-generic
    version: *osmosis_version
  su-exec:
    image: rpmbuild-generic
    version: *suexec_version
  stxxl:
    image: rpmbuild-generic
    version: *stxxl_version
  tomcat8:
    image: rpmbuild-generic
    version: *tomcat8_version
