---
versions:
  glpk: &glpk_version '4.65-1'
  hoot-words: &words_version '1.0.1-1'
  liboauthcpp: &liboauthcpp_version '0.1.0-1'
  libphonenumber: &libphonenumber_version '8.12.26-1'
  libpostal: &libpostal_version '1.0.0-1'
  mocha: &mocha_version '3.5.3'
  nodejs: &nodejs_version '14.16.1-1'
  npm: &npm_version '6.14.12-1'
  postgresql: &pg_version '9.5'
  stxxl: &stxxl_version '1.3.1-1'
  hoot-translations-templates: &hoot_translations_templates_version '1.0.0-1'
  tomcat8: &tomcat8_version '8.5.66-1'
  v8: &v8_version '8.4.371.19-1'
  wamerican-insane: &wamerican_version '7.1-1'


maven:
  cache_url: &maven_cache_url 'https://s3.amazonaws.com/hoot-maven/m2-cache-2018-12-06.tar.gz'
  cache_sha1: &maven_cache_sha1 'c6e87f8100c9461c00b7d28a5a8d0e8b1737ccf3'


rpmbuild:
  dist: &rpmbuild_dist '.el7'
  uid: &rpmbuild_uid 1000


images:
  base: !!omap
    - rpmbuild:
        args:
          rpmbuild_dist: *rpmbuild_dist
          rpmbuild_uid: *rpmbuild_uid
          rpmbuild_gid: *rpmbuild_uid
    - rpmbuild-base: {}
    - rpmbuild-generic: {}
    - rpmbuild-pgdg:
        args:
          pg_version: *pg_version
        tags: [*pg_version]
    - rpmbuild-hoot-release:
        args:
          mocha_version: *mocha_version
          nodejs_version: *nodejs_version
          pg_version: *pg_version
        buildrequires: true
        rpmbuild: true
        spec_file: 'SPECS/hootenanny.spec'
    - rpmbuild-lint: {}
    - rpmbuild-repo: {}
    - rpmbuild-sonarqube: {}
    - rpmbuild-glpk:
        buildrequires: true
        dockerfile: 'docker/Dockerfile.rpmbuild-generic'
    - rpmbuild-liboauthcpp:
        buildrequires: true
        dockerfile: 'docker/Dockerfile.rpmbuild-generic'
    - rpmbuild-libphonenumber:
        buildrequires: true
        dockerfile: 'docker/Dockerfile.rpmbuild-generic'
    - rpmbuild-libpostal: {}
    - rpmbuild-nodejs:
        buildrequires: true
    - run-base:
        args:
          pg_version: *pg_version
    - run-base-release:
        args:
          mocha_version: *mocha_version
          nodejs_version: *nodejs_version
  hoot: !!omap
    - rpmbuild-hoot-devel:
        args:
          glpk_version: *glpk_version
          liboauthcpp_version: *liboauthcpp_version
          libphonenumber_version: *libphonenumber_version
          libpostal_version: *libpostal_version
          mocha_version: *mocha_version
          nodejs_version: *nodejs_version
          npm_version: *npm_version
          pg_version: *pg_version
          stxxl_version: *stxxl_version
          tomcat8_version: *tomcat8_version
          v8_version: *v8_version
          words_version: *words_version
        buildrequires: true
        rpmbuild: true
        spec_file: 'SPECS/hootenanny.spec'
    - run-base-devel:
        args:
          glpk_version: *glpk_version
          mocha_version: *mocha_version
          nodejs_version: *nodejs_version
          npm_version: *npm_version
          pg_version: *pg_version
          stxxl_version: *stxxl_version
          tomcat8_version: *tomcat8_version
          v8_version: *v8_version
          words_version: *words_version
        rpmbuild: true

rpms:
  glpk:
    image: rpmbuild-glpk
    version: *glpk_version
  hoot-words:
    image: rpmbuild-generic
    version: *words_version
    arch: noarch
  hoot-translations-templates:
    image: rpmbuild-generic
    version: *hoot_translations_templates_version
    arch: noarch
  liboauthcpp:
    image: rpmbuild-liboauthcpp
    version: *liboauthcpp_version
  libphonenumber:
    image: rpmbuild-libphonenumber
    version: *libphonenumber_version
  libpostal:
    image: rpmbuild-libpostal
    version: *libpostal_version
  nodejs:
    image: rpmbuild-nodejs
    version: *nodejs_version
  stxxl:
    image: rpmbuild-generic
    version: *stxxl_version
  tomcat8:
    image: rpmbuild-generic
    version: *tomcat8_version
    arch: noarch
  wamerican-insane:
    image: rpmbuild-generic
    version: *wamerican_version
    arch: noarch
