---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:34d389aad27cb6cd10d158063718d5e47d7a7d96d2211e0bbe8f621f57803fa8
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            export RPMBUILD_UID_MATCH=1
            make rpmbuild-hoot-release
  develop-rpm:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Develop RPM'
          command: |
            set -x
            mkdir -p cache/m2 cache/npm el7/develop RPMS
            LATEST_ARCHIVE="$(./scripts/latest-archive.sh -b hoot-archives -p circle/develop)"
            if [ "$(./scripts/query-archive.sh -a $LATEST_ARCHIVE -b hoot-repo -p el7/develop/)" = "0" ]; then
                aws s3 cp s3://hoot-archives/$LATEST_ARCHIVE SOURCES/
                source shell/Vars.sh
                maven_cache
                sudo chown -R 1000:1000 cache RPMS SOURCES
                ./shell/BuildHoot.sh
                sudo mv -v RPMS/{noarch,x86_64}/*.rpm el7/develop
            else
                touch el7/develop/none.rpm
            fi
            sudo chown -R 1000:1000 el7/develop
      - persist_to_workspace:
          root: el7/develop
          paths:
            - "*.rpm"
  develop-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:7147b62b7a6dded4b72003df0aca52ab4b667dba4da5c11a7ceb4b00bbacd120
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7/develop
      - run:
          name: 'Update and Sync Develop Repository'
          command: |
            set -x
            if [ -f el7/develop/none.rpm ]; then
                echo "RPM has already been created."
            else
                ./scripts/repo-sync.sh -b hoot-repo -p el7/develop
            fi

workflows:
  version: 2
  develop-repo:
    jobs:
      - develop-rpm
      - develop-sync:
          requires:
            - develop-rpm
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
