---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:105824d72d650b30a404ea3197c28b2c341c0a033ac2f20456e97a702d2a3baa
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
  master-rpm:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Master RPM'
          command: |
            ./tests/create-rpm.sh
      - persist_to_workspace:
          root: el7
          paths:
            - "*.rpm"
  master-install:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:40fb04610bc0e3317f5a7c7cef95b49b1996863c3323f4ab6fc316a9526f9cc0
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Installation'
          command: |
            ./tests/install-rpm.sh
  master-upgrade:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:40fb04610bc0e3317f5a7c7cef95b49b1996863c3323f4ab6fc316a9526f9cc0
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Upgrade'
          command: |
            ./tests/upgrade-rpm.sh
  master-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:27c86924043bae5d291bbc203702d2b2ed9f6970d9647462ecb8c73df5e012b4
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Update and Sync Master Repository'
          command: |
            ./tests/update-sync-repo.sh

workflows:
  version: 2
  master-repo:
    jobs:
      - master-rpm
      - master-install:
          requires:
            - master-rpm
      - master-upgrade:
          requires:
            - master-rpm
      - master-sync:
          requires:
            - master-install
            - master-upgrade
    triggers:
      - schedule:
          cron: "0 12,20 * * *"
          filters:
            branches:
              only:
                - master
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
