---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:34d389aad27cb6cd10d158063718d5e47d7a7d96d2211e0bbe8f621f57803fa8
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
  develop-rpm:
    machine:
      enabled: true
    environment:
      REPO_PREFIX: el7/develop-test
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Develop RPM'
          command: |
            ./tests/create-rpm.sh
      - persist_to_workspace:
          root: el7
          paths:
            - "*.rpm"
  develop-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:7147b62b7a6dded4b72003df0aca52ab4b667dba4da5c11a7ceb4b00bbacd120
        environment:
          REPO_PREFIX: el7/develop-test
          SLACK_NOTIFY: 'no'
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Update and Sync Develop Repository'
          command: |
            ./tests/update-sync-repo.sh

workflows:
  version: 2
  develop-repo:
    jobs:
      - develop-rpm
      - develop-sync:
          requires:
            - develop-rpm
    filters:
      branches:
        only:
          - test-scripts
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
