---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:0d554c52e05243a0cc54fb0c0ffc2c46a237e3d384e07cf92ec52627d0822745
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
  master-rpm:
    machine:
      enabled: true
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Master RPM'
          command: |
            ./tests/create-rpm.sh
      - persist_to_workspace:
          root: el7
          paths:
            - "*.rpm"
  master-install:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:770afcafbc2e1c21ef76ddd4a3c3fb45df6f9a3be7d09a25dab29ac914b1121f
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Installation'
          command: |
            ./tests/install-rpm.sh
  master-upgrade:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:770afcafbc2e1c21ef76ddd4a3c3fb45df6f9a3be7d09a25dab29ac914b1121f
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Upgrade'
          command: |
            ./tests/upgrade-rpm.sh
  master-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:5f4bb14e00a60ab66579edb2382135d5609ead01d5bde6f0a9cd0a3203a8d520
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Update and Sync Master Repository'
          command: |
            ./tests/update-sync-repo.sh

workflows:
  version: 2
  # Always run the RPM workflow on merges to master to take into account
  # any SPEC changes and to make it possible to force a RPM rebuild at
  # any time.
  master-rpm:
    jobs:
      - master-rpm:
          filters: &filters-master
            branches:
              only:
                - master
      - master-install:
          requires:
            - master-rpm
          filters: *filters-master
      - master-upgrade:
          requires:
            - master-rpm
          filters: *filters-master
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
