---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:08b8b84afff7fcbe332c155b1eddfa0c38d307d6e9c039da3064bbe31d5d539d
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
      image: ubuntu-2004:202111-02
      resource_class: large
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
  master-rpm:
    machine:
      enabled: true
      image: ubuntu-2004:202111-02
      resource_class: large
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Master RPM'
          command: |
            ./tests/create-rpm.sh
      - persist_to_workspace:
          root: el7
          paths:
            - "*.rpm"
  master-install:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:64b8ce1632e3ae4155e73e46c714e93ea14fc7b66ffa99a16c715b6aa8f94e42
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Installation'
          command: |
            ./tests/install-rpm.sh
  master-upgrade:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:64b8ce1632e3ae4155e73e46c714e93ea14fc7b66ffa99a16c715b6aa8f94e42
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Upgrade'
          command: |
            ./tests/upgrade-rpm.sh
  master-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:885934cb06bf3710909f591afb9cfa3ae9bcc1711f6a7837828079a57ed6ce16
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Update and Sync Master Repository'
          command: |
            ./tests/update-sync-repo.sh

workflows:
  version: 2
  master-repo:
    jobs:
      - master-rpm
      - master-install: &master-install
          requires:
            - master-rpm
      - master-upgrade: &master-upgrade
          requires:
            - master-rpm
      - master-sync: &master-sync
          requires:
            - master-install
            - master-upgrade
    triggers:
      - schedule:
          cron: "0 5,17 * * *"
          filters: &filters-master
            branches:
              only:
                - master
  # Always run the RPM workflow on merges to master to take into account
  # any SPEC changes and to make it possible to force a RPM rebuild at
  # any time.
  master-rpm:
    jobs:
      - master-rpm:
          filters: *filters-master
      - master-install:
          <<: *master-install
          filters: *filters-master
      - master-upgrade:
          <<: *master-upgrade
          filters: *filters-master
      - master-sync:
          <<: *master-sync
          filters: *filters-master
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
