---
version: 2

jobs:
  lint:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-lint@sha256:1e7018346b8e364d7cb085531bb6196b6b3efbcf3d93b4f1cf0ffbc0cae0405d
        user: rpmbuild
    steps:
      - checkout
      - run:
          name: 'Lint YAML and Scripts'
          command: |
            ./tests/lint-yaml.sh
            ./tests/lint-bash.sh
  rpmbuild-hoot-release:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools and Vagrant'
          command: |
            ./scripts/rpm-install.sh
            ./scripts/vagrant-install.sh
      - run:
          name: 'Validate Vagrantfile'
          command: |
            MAVEN_CACHE=0 vagrant validate
      - run:
          name: 'Building rpmbuild-hoot-release'
          command: |
            make rpmbuild-hoot-release
  develop-rpm:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: 'Install RPM Tools'
          command: |
            ./scripts/rpm-install.sh
      - run:
          name: 'Compile Latest Develop RPM'
          command: |
            ./tests/create-rpm.sh
      - persist_to_workspace:
          root: el7
          paths:
            - "*.rpm"
  develop-install:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:f5e356452e887e82bb8dac3156b61f143443bcdac608988ccc42a92771f54b27
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Installation'
          command: |
            ./tests/install-rpm.sh
  develop-upgrade:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/run-base-release@sha256:f5e356452e887e82bb8dac3156b61f143443bcdac608988ccc42a92771f54b27
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Test RPM Upgrade'
          command: |
            ./tests/upgrade-rpm.sh
  develop-sync:
    working_directory: '/rpmbuild/hootenanny-rpms'
    docker:
      - image: hootenanny/rpmbuild-repo@sha256:3188fdacecb7ae5659e0274828b66da4b000f37357ad6bd71478a82137c35eea
        user: rpmbuild
    steps:
      - checkout
      - attach_workspace:
          at: el7
      - run:
          name: 'Update and Sync Develop Repository'
          command: |
            ./tests/update-sync-repo.sh

workflows:
  version: 2
  develop-repo:
    jobs:
      - develop-rpm
      - develop-install:
          requires:
            - develop-rpm
      - develop-upgrade:
          requires:
            - develop-rpm
      - develop-sync:
          requires:
            - develop-install
            - develop-upgrade
    triggers:
      - schedule:
          cron: "0 12,20 * * *"
          filters:
            branches:
              only:
                - develop
  tests:
    jobs:
      - lint
      - rpmbuild-hoot-release
